// Code generated by protoc-gen-protocomm-go. DO NOT EDIT.
// source: calculator.proto

package math

import (
	_go "github.com/boeing666/protocomm/go"
	proto "google.golang.org/protobuf/proto"
)

// Method IDs for Calculator service.
const (
	Calculator_Add_MethodID      uint32 = 0x5e1a1ae6 // /math.Calculator/Add
	Calculator_Subtract_MethodID uint32 = 0x117c9a17 // /math.Calculator/Subtract
	Calculator_Multiply_MethodID uint32 = 0x6eaa896b // /math.Calculator/Multiply
	Calculator_Divide_MethodID   uint32 = 0x88abc36a // /math.Calculator/Divide
)

// CalculatorClient is the client stub for the Calculator service.
type CalculatorClient struct {
	ch *_go.Channel
}

// NewCalculatorClient creates a client stub bound to the given channel.
func NewCalculatorClient(ch *_go.Channel) *CalculatorClient {
	return &CalculatorClient{ch: ch}
}

func (c *CalculatorClient) Add(req *CalcRequest) (*CalcResponse, _go.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, _go.Status{Code: _go.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Calculator_Add_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(CalcResponse)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, _go.Status{Code: _go.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, _go.StatusOK()
}

func (c *CalculatorClient) Subtract(req *CalcRequest) (*CalcResponse, _go.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, _go.Status{Code: _go.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Calculator_Subtract_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(CalcResponse)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, _go.Status{Code: _go.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, _go.StatusOK()
}

func (c *CalculatorClient) Multiply(req *CalcRequest) (*CalcResponse, _go.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, _go.Status{Code: _go.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Calculator_Multiply_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(CalcResponse)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, _go.Status{Code: _go.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, _go.StatusOK()
}

func (c *CalculatorClient) Divide(req *CalcRequest) (*CalcResponse, _go.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, _go.Status{Code: _go.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Calculator_Divide_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(CalcResponse)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, _go.Status{Code: _go.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, _go.StatusOK()
}

// CalculatorServer is the server-side interface for the Calculator service.
type CalculatorServer interface {
	Add(ctx *_go.ServerContext, req *CalcRequest) (*CalcResponse, _go.Status)
	Subtract(ctx *_go.ServerContext, req *CalcRequest) (*CalcResponse, _go.Status)
	Multiply(ctx *_go.ServerContext, req *CalcRequest) (*CalcResponse, _go.Status)
	Divide(ctx *_go.ServerContext, req *CalcRequest) (*CalcResponse, _go.Status)
}

// UnimplementedCalculatorServer returns UNIMPLEMENTED for every method.
type UnimplementedCalculatorServer struct{}

func (UnimplementedCalculatorServer) Add(_ *_go.ServerContext, _ *CalcRequest) (*CalcResponse, _go.Status) {
	return nil, _go.Status{Code: _go.Unimplemented, Message: "Add not implemented"}
}

func (UnimplementedCalculatorServer) Subtract(_ *_go.ServerContext, _ *CalcRequest) (*CalcResponse, _go.Status) {
	return nil, _go.Status{Code: _go.Unimplemented, Message: "Subtract not implemented"}
}

func (UnimplementedCalculatorServer) Multiply(_ *_go.ServerContext, _ *CalcRequest) (*CalcResponse, _go.Status) {
	return nil, _go.Status{Code: _go.Unimplemented, Message: "Multiply not implemented"}
}

func (UnimplementedCalculatorServer) Divide(_ *_go.ServerContext, _ *CalcRequest) (*CalcResponse, _go.Status) {
	return nil, _go.Status{Code: _go.Unimplemented, Message: "Divide not implemented"}
}

// RegisterCalculatorServer registers a CalculatorServer with the protocomm server.
func RegisterCalculatorServer(srv *_go.Server, impl CalculatorServer) {
	srv.RegisterMethod(Calculator_Add_MethodID, func(ctx *_go.ServerContext, data []byte) ([]byte, _go.Status) {
		req := new(CalcRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, _go.Status{Code: _go.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.Add(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, _go.Status{Code: _go.Internal, Message: "marshal: " + err.Error()}
		}
		return out, _go.StatusOK()
	})
	srv.RegisterMethod(Calculator_Subtract_MethodID, func(ctx *_go.ServerContext, data []byte) ([]byte, _go.Status) {
		req := new(CalcRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, _go.Status{Code: _go.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.Subtract(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, _go.Status{Code: _go.Internal, Message: "marshal: " + err.Error()}
		}
		return out, _go.StatusOK()
	})
	srv.RegisterMethod(Calculator_Multiply_MethodID, func(ctx *_go.ServerContext, data []byte) ([]byte, _go.Status) {
		req := new(CalcRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, _go.Status{Code: _go.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.Multiply(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, _go.Status{Code: _go.Internal, Message: "marshal: " + err.Error()}
		}
		return out, _go.StatusOK()
	})
	srv.RegisterMethod(Calculator_Divide_MethodID, func(ctx *_go.ServerContext, data []byte) ([]byte, _go.Status) {
		req := new(CalcRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, _go.Status{Code: _go.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.Divide(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, _go.Status{Code: _go.Internal, Message: "marshal: " + err.Error()}
		}
		return out, _go.StatusOK()
	})
}

type calculatorServiceRegistrar struct{ impl CalculatorServer }

func (r *calculatorServiceRegistrar) RegisterWith(srv *_go.Server) {
	RegisterCalculatorServer(srv, r.impl)
}

// NewCalculatorService wraps impl as a _go.Service for use with ServerBuilder.
func NewCalculatorService(impl CalculatorServer) _go.Service {
	return &calculatorServiceRegistrar{impl: impl}
}
