// Code generated by protoc-gen-protocomm-go. DO NOT EDIT.
// source: example.proto

package example

import (
	proto "google.golang.org/protobuf/proto"
	protocomm "protocomm"
)

// Method IDs for Greeter service.
const (
	Greeter_SayHello_MethodID  uint32 = 0x18500478 // /Greeter/SayHello
	Greeter_SayHello1_MethodID uint32 = 0x8ef6beeb // /Greeter/SayHello1
	Greeter_SayHello2_MethodID uint32 = 0x8ff6c07e // /Greeter/SayHello2
	Greeter_SayHello3_MethodID uint32 = 0x90f6c211 // /Greeter/SayHello3
	Greeter_SayHello4_MethodID uint32 = 0x91f6c3a4 // /Greeter/SayHello4
	Greeter_SayHello5_MethodID uint32 = 0x92f6c537 // /Greeter/SayHello5
	Greeter_SayHello6_MethodID uint32 = 0x93f6c6ca // /Greeter/SayHello6
	Greeter_SayHello7_MethodID uint32 = 0x94f6c85d // /Greeter/SayHello7
	Greeter_SayHello8_MethodID uint32 = 0x85f6b0c0 // /Greeter/SayHello8
)

// GreeterClient is the client stub for the Greeter service.
type GreeterClient struct {
	ch *protocomm.Channel
}

// NewGreeterClient creates a client stub bound to the given channel.
func NewGreeterClient(ch *protocomm.Channel) *GreeterClient {
	return &GreeterClient{ch: ch}
}

func (c *GreeterClient) SayHello(req *HelloRequest) (*HelloReply, protocomm.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Greeter_SayHello_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(HelloReply)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, protocomm.StatusOK()
}

func (c *GreeterClient) SayHello1(req *HelloRequest) (*HelloReply, protocomm.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Greeter_SayHello1_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(HelloReply)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, protocomm.StatusOK()
}

func (c *GreeterClient) SayHello2(req *HelloRequest) (*HelloReply, protocomm.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Greeter_SayHello2_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(HelloReply)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, protocomm.StatusOK()
}

func (c *GreeterClient) SayHello3(req *HelloRequest) (*HelloReply, protocomm.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Greeter_SayHello3_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(HelloReply)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, protocomm.StatusOK()
}

func (c *GreeterClient) SayHello4(req *HelloRequest) (*HelloReply, protocomm.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Greeter_SayHello4_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(HelloReply)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, protocomm.StatusOK()
}

func (c *GreeterClient) SayHello5(req *HelloRequest) (*HelloReply, protocomm.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Greeter_SayHello5_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(HelloReply)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, protocomm.StatusOK()
}

func (c *GreeterClient) SayHello6(req *HelloRequest) (*HelloReply, protocomm.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Greeter_SayHello6_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(HelloReply)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, protocomm.StatusOK()
}

func (c *GreeterClient) SayHello7(req *HelloRequest) (*HelloReply, protocomm.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Greeter_SayHello7_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(HelloReply)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, protocomm.StatusOK()
}

func (c *GreeterClient) SayHello8(req *HelloRequest) (*HelloReply, protocomm.Status) {
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
	}
	respData, st := c.ch.UnaryCall(Greeter_SayHello8_MethodID, data)
	if !st.IsOK() {
		return nil, st
	}
	resp := new(HelloReply)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
	}
	return resp, protocomm.StatusOK()
}

// GreeterServer is the server-side interface for the Greeter service.
type GreeterServer interface {
	SayHello(ctx *protocomm.ServerContext, req *HelloRequest) (*HelloReply, protocomm.Status)
	SayHello1(ctx *protocomm.ServerContext, req *HelloRequest) (*HelloReply, protocomm.Status)
	SayHello2(ctx *protocomm.ServerContext, req *HelloRequest) (*HelloReply, protocomm.Status)
	SayHello3(ctx *protocomm.ServerContext, req *HelloRequest) (*HelloReply, protocomm.Status)
	SayHello4(ctx *protocomm.ServerContext, req *HelloRequest) (*HelloReply, protocomm.Status)
	SayHello5(ctx *protocomm.ServerContext, req *HelloRequest) (*HelloReply, protocomm.Status)
	SayHello6(ctx *protocomm.ServerContext, req *HelloRequest) (*HelloReply, protocomm.Status)
	SayHello7(ctx *protocomm.ServerContext, req *HelloRequest) (*HelloReply, protocomm.Status)
	SayHello8(ctx *protocomm.ServerContext, req *HelloRequest) (*HelloReply, protocomm.Status)
}

// UnimplementedGreeterServer returns UNIMPLEMENTED for every method.
type UnimplementedGreeterServer struct{}

func (UnimplementedGreeterServer) SayHello(_ *protocomm.ServerContext, _ *HelloRequest) (*HelloReply, protocomm.Status) {
	return nil, protocomm.Status{Code: protocomm.Unimplemented, Message: "SayHello not implemented"}
}

func (UnimplementedGreeterServer) SayHello1(_ *protocomm.ServerContext, _ *HelloRequest) (*HelloReply, protocomm.Status) {
	return nil, protocomm.Status{Code: protocomm.Unimplemented, Message: "SayHello1 not implemented"}
}

func (UnimplementedGreeterServer) SayHello2(_ *protocomm.ServerContext, _ *HelloRequest) (*HelloReply, protocomm.Status) {
	return nil, protocomm.Status{Code: protocomm.Unimplemented, Message: "SayHello2 not implemented"}
}

func (UnimplementedGreeterServer) SayHello3(_ *protocomm.ServerContext, _ *HelloRequest) (*HelloReply, protocomm.Status) {
	return nil, protocomm.Status{Code: protocomm.Unimplemented, Message: "SayHello3 not implemented"}
}

func (UnimplementedGreeterServer) SayHello4(_ *protocomm.ServerContext, _ *HelloRequest) (*HelloReply, protocomm.Status) {
	return nil, protocomm.Status{Code: protocomm.Unimplemented, Message: "SayHello4 not implemented"}
}

func (UnimplementedGreeterServer) SayHello5(_ *protocomm.ServerContext, _ *HelloRequest) (*HelloReply, protocomm.Status) {
	return nil, protocomm.Status{Code: protocomm.Unimplemented, Message: "SayHello5 not implemented"}
}

func (UnimplementedGreeterServer) SayHello6(_ *protocomm.ServerContext, _ *HelloRequest) (*HelloReply, protocomm.Status) {
	return nil, protocomm.Status{Code: protocomm.Unimplemented, Message: "SayHello6 not implemented"}
}

func (UnimplementedGreeterServer) SayHello7(_ *protocomm.ServerContext, _ *HelloRequest) (*HelloReply, protocomm.Status) {
	return nil, protocomm.Status{Code: protocomm.Unimplemented, Message: "SayHello7 not implemented"}
}

func (UnimplementedGreeterServer) SayHello8(_ *protocomm.ServerContext, _ *HelloRequest) (*HelloReply, protocomm.Status) {
	return nil, protocomm.Status{Code: protocomm.Unimplemented, Message: "SayHello8 not implemented"}
}

// RegisterGreeterServer registers a GreeterServer with the protocomm server.
func RegisterGreeterServer(srv *protocomm.Server, impl GreeterServer) {
	srv.RegisterMethod(Greeter_SayHello_MethodID, func(ctx *protocomm.ServerContext, data []byte) ([]byte, protocomm.Status) {
		req := new(HelloRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.SayHello(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
		}
		return out, protocomm.StatusOK()
	})
	srv.RegisterMethod(Greeter_SayHello1_MethodID, func(ctx *protocomm.ServerContext, data []byte) ([]byte, protocomm.Status) {
		req := new(HelloRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.SayHello1(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
		}
		return out, protocomm.StatusOK()
	})
	srv.RegisterMethod(Greeter_SayHello2_MethodID, func(ctx *protocomm.ServerContext, data []byte) ([]byte, protocomm.Status) {
		req := new(HelloRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.SayHello2(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
		}
		return out, protocomm.StatusOK()
	})
	srv.RegisterMethod(Greeter_SayHello3_MethodID, func(ctx *protocomm.ServerContext, data []byte) ([]byte, protocomm.Status) {
		req := new(HelloRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.SayHello3(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
		}
		return out, protocomm.StatusOK()
	})
	srv.RegisterMethod(Greeter_SayHello4_MethodID, func(ctx *protocomm.ServerContext, data []byte) ([]byte, protocomm.Status) {
		req := new(HelloRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.SayHello4(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
		}
		return out, protocomm.StatusOK()
	})
	srv.RegisterMethod(Greeter_SayHello5_MethodID, func(ctx *protocomm.ServerContext, data []byte) ([]byte, protocomm.Status) {
		req := new(HelloRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.SayHello5(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
		}
		return out, protocomm.StatusOK()
	})
	srv.RegisterMethod(Greeter_SayHello6_MethodID, func(ctx *protocomm.ServerContext, data []byte) ([]byte, protocomm.Status) {
		req := new(HelloRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.SayHello6(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
		}
		return out, protocomm.StatusOK()
	})
	srv.RegisterMethod(Greeter_SayHello7_MethodID, func(ctx *protocomm.ServerContext, data []byte) ([]byte, protocomm.Status) {
		req := new(HelloRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.SayHello7(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
		}
		return out, protocomm.StatusOK()
	})
	srv.RegisterMethod(Greeter_SayHello8_MethodID, func(ctx *protocomm.ServerContext, data []byte) ([]byte, protocomm.Status) {
		req := new(HelloRequest)
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "unmarshal: " + err.Error()}
		}
		resp, st := impl.SayHello8(ctx, req)
		if !st.IsOK() {
			return nil, st
		}
		out, err := proto.Marshal(resp)
		if err != nil {
			return nil, protocomm.Status{Code: protocomm.Internal, Message: "marshal: " + err.Error()}
		}
		return out, protocomm.StatusOK()
	})
}

type greeterServiceRegistrar struct{ impl GreeterServer }

func (r *greeterServiceRegistrar) RegisterWith(srv *protocomm.Server) {
	RegisterGreeterServer(srv, r.impl)
}

// NewGreeterService wraps impl as a protocomm.Service for use with ServerBuilder.
func NewGreeterService(impl GreeterServer) protocomm.Service {
	return &greeterServiceRegistrar{impl: impl}
}
