#include "generator.hpp"
#include "generator_utils.hpp"

namespace protocomm {
namespace gen {

namespace {

std::string InputTypeCpp(const google::protobuf::MethodDescriptorProto& m) {
    return proto_type_to_cpp(m.input_type());
}

std::string OutputTypeCpp(const google::protobuf::MethodDescriptorProto& m) {
    return proto_type_to_cpp(m.output_type());
}

void EmitPreamble(std::string& code, const ServiceContext& ctx) {
    std::string file_name = ctx.file.name();
    std::string pb_header = file_name.substr(0, file_name.find_last_of('.')) + ".pb.h";

    code += "// Generated by protoc-gen-protocomm.  DO NOT EDIT!\n";
    code += "// source: " + file_name + "\n\n";
    code += "#pragma once\n\n";
    code += "#include <cstdint>\n";
    code += "#include <functional>\n";
    code += "#include <future>\n";
    code += "#include <memory>\n";
    code += "#include <string>\n";
    code += "#include <utility>\n\n";
    code += "#include \"" + pb_header + "\"\n";
    code += "#include \"protocomm/async_call.h\"\n";
    code += "#include \"protocomm/channel.h\"\n";
    code += "#include \"protocomm/connection.h\"\n";
    code += "#include \"protocomm/method_hash.h\"\n";
    code += "#include \"protocomm/protobuf.h\"\n";
    code += "#include \"protocomm/server.h\"\n";
    code += "#include \"protocomm/server_context.h\"\n";
    code += "#include \"protocomm/service.h\"\n";
    code += "#include \"protocomm/status.h\"\n\n";

    if (ctx.has_ns) {
        code += "namespace " + ctx.ns + " {\n\n";
    }
}

void EmitMethodConstants(std::string& code, const ServiceContext& ctx) {
    for (const auto& m : ctx.svc.method()) {
        std::string key = method_full_name(ctx.pkg, ctx.svc_name, m.name());
        code += "    static constexpr uint32_t k" + m.name()
             +  "MethodId = ::protocomm::Fnv1a32(\"" + key + "\");\n";
    }
    code += "\n";
}

void EmitStubClass(std::string& code, const ServiceContext& ctx) {
    const std::string& svc = ctx.svc_name;

    code += "    class Stub {\n";
    code += "    public:\n";
    code += "        explicit Stub(std::shared_ptr<::protocomm::ChannelInterface> channel)\n";
    code += "            : channel_(std::move(channel)) {}\n\n";

    for (const auto& m : ctx.svc.method()) {
        std::string in = InputTypeCpp(m);
        std::string out = OutputTypeCpp(m);
        std::string method = m.name();
        std::string mid = "k" + method + "MethodId";
        std::string full = ctx.svc_name + "." + method;

        code += "        ::protocomm::Status " + method + "(\n";
        code += "                const " + in + "& request,\n";
        code += "                " + out + "* response) {\n";
        code += "            std::string req_bytes, resp_bytes;\n";
        code += "            ::protocomm::Status s = ::protocomm::SerializeProto(request, req_bytes);\n";
        code += "            if (!s.ok()) return s;\n";
        code += "            const bool trace = channel_->Tracing();\n";
        code += "            s = channel_->UnaryCall(" + mid + ", req_bytes, &resp_bytes);\n";
        code += "            if (!s.ok()) {\n";
        code += "                if (trace) channel_->OnTrace(\"" + full + "\", ::protocomm::RenderProto(request), {}, s);\n";
        code += "                return s;\n";
        code += "            }\n";
        code += "            ::protocomm::Status ps = ::protocomm::ParseProto(resp_bytes, *response);\n";
        code += "            if (trace)\n";
        code += "                channel_->OnTrace(\"" + full + "\", ::protocomm::RenderProto(request),\n";
        code += "                                  ps.ok() ? ::protocomm::RenderProto(*response) : std::string{}, ps);\n";
        code += "            return ps;\n";
        code += "        }\n\n";

        code += "        ::protocomm::AsyncUnaryCall<" + out + "> Async" + method + "(\n";
        code += "                const " + in + "& request) {\n";
        code += "            std::string req_bytes;\n";
        code += "            ::protocomm::Status ser = ::protocomm::SerializeProto(request, req_bytes);\n";
        code += "            if (!ser.ok()) {\n";
        code += "                std::promise<std::pair<::protocomm::Status, std::string>> p;\n";
        code += "                p.set_value({ser, {}});\n";
        code += "                return ::protocomm::AsyncUnaryCall<" + out + ">(p.get_future());\n";
        code += "            }\n";
        code += "            return ::protocomm::AsyncUnaryCall<" + out + ">(\n";
        code += "                channel_->AsyncUnaryCall(" + mid + ", std::move(req_bytes)));\n";
        code += "        }\n\n";

        code += "        void Async" + method + "(\n";
        code += "                const " + in + "& request,\n";
        code += "                std::function<void(::protocomm::Status, " + out + ")> on_response) {\n";
        code += "            std::string req_bytes;\n";
        code += "            ::protocomm::Status ser = ::protocomm::SerializeProto(request, req_bytes);\n";
        code += "            if (!ser.ok()) {\n";
        code += "                if (on_response) on_response(ser, " + out + "{});\n";
        code += "                return;\n";
        code += "            }\n";
        // Capture the channel (shared_ptr) — the Stub is often a temporary that dies before
        // the async reply arrives, so the callback must keep the channel, not `this`.
        code += "            auto ch = channel_;\n";
        code += "            const bool trace = ch->Tracing();\n";
        code += "            std::string req_text = trace ? ::protocomm::RenderProto(request) : std::string{};\n";
        code += "            ch->AsyncUnaryCall(" + mid + ", std::move(req_bytes),\n";
        code += "                [ch, cb = std::move(on_response), trace, req_text = std::move(req_text)]\n";
        code += "                (::protocomm::Status st, std::string bytes) {\n";
        code += "                    " + out + " resp;\n";
        code += "                    ::protocomm::Status ps = st;\n";
        code += "                    if (st.ok()) ps = ::protocomm::ParseProto(bytes, resp);\n";
        code += "                    if (trace)\n";
        code += "                        ch->OnTrace(\"" + full + "\", req_text,\n";
        code += "                                    (st.ok() && ps.ok()) ? ::protocomm::RenderProto(resp) : std::string{},\n";
        code += "                                    ps.ok() ? st : ps);\n";
        code += "                    if (!cb) return;\n";
        code += "                    if (!st.ok()) { cb(st, " + out + "{}); return; }\n";
        code += "                    if (!ps.ok()) { cb(ps, " + out + "{}); return; }\n";
        code += "                    cb(::protocomm::Status{}, std::move(resp));\n";
        code += "                });\n";
        code += "        }\n\n";
    }

    code += "    private:\n";
    code += "        std::shared_ptr<::protocomm::ChannelInterface> channel_;\n";
    code += "    };\n\n";
}

void EmitPeerWriterClass(std::string& code, const ServiceContext& ctx) {
    code += "    class PeerWriter {\n";
    code += "    public:\n";
    code += "        explicit PeerWriter(std::shared_ptr<::protocomm::Peer> peer)\n";
    code += "            : peer_(std::move(peer)) {}\n\n";
    code += "        uint64_t id() const { return peer_->id(); }\n";
    code += "        const std::string& peer_address() const { return peer_->peer_address(); }\n";
    code += "        void Close() { peer_->Close(); }\n";
    code += "        const std::shared_ptr<::protocomm::Peer>& peer() const { return peer_; }\n\n";

    for (const auto& m : ctx.svc.method()) {
        std::string out = OutputTypeCpp(m);
        std::string method = m.name();
        std::string mid = "k" + method + "MethodId";

        code += "        void Send" + method + "(const " + out + "& message) {\n";
        code += "            std::string bytes;\n";
        code += "            ::protocomm::SerializeProto(message, bytes);\n";
        code += "            peer_->Send(" + mid + ", bytes);\n";
        code += "        }\n\n";
    }

    code += "    private:\n";
    code += "        std::shared_ptr<::protocomm::Peer> peer_;\n";
    code += "    };\n\n";
}

void EmitBroadcasterClass(std::string& code, const ServiceContext& ctx) {
    code += "    class Broadcaster {\n";
    code += "    public:\n";
    code += "        explicit Broadcaster(::protocomm::Server* server)\n";
    code += "            : server_(server) {}\n\n";

    for (const auto& m : ctx.svc.method()) {
        std::string out = OutputTypeCpp(m);
        std::string method = m.name();
        std::string mid = "k" + method + "MethodId";

        code += "        void Broadcast" + method + "(const " + out + "& message) {\n";
        code += "            std::string bytes;\n";
        code += "            ::protocomm::SerializeProto(message, bytes);\n";
        code += "            server_->Broadcast(" + mid + ", bytes);\n";
        code += "        }\n\n";
    }

    code += "    private:\n";
    code += "        ::protocomm::Server* server_;\n";
    code += "    };\n\n";
}

void EmitServiceClass(std::string& code, const ServiceContext& ctx) {
    const std::string& svc = ctx.svc_name;

    code += "    class Service : public ::protocomm::Service {\n";
    code += "    public:\n";

    for (const auto& m : ctx.svc.method()) {
        std::string in = InputTypeCpp(m);
        std::string out = OutputTypeCpp(m);
        code += "        virtual ::protocomm::Status " + m.name() + "(\n";
        code += "                ::protocomm::ServerContext* /*ctx*/,\n";
        code += "                const " + in + "* /*request*/,\n";
        code += "                " + out + "* /*response*/) {\n";
        code += "            return {::protocomm::StatusCode::UNIMPLEMENTED, \"" + m.name() + " not implemented\"};\n";
        code += "        }\n\n";
    }

    code += "        void RegisterWith(::protocomm::Server* server) override {\n";
    for (const auto& m : ctx.svc.method()) {
        std::string in = InputTypeCpp(m);
        std::string out = OutputTypeCpp(m);
        std::string mid = "k" + m.name() + "MethodId";
        std::string full = svc + "." + m.name();
        code += "            server->RegisterMethod(" + mid + ",\n";
        code += "                [this](::protocomm::ServerContext* ctx,\n";
        code += "                       const std::string& req_bytes,\n";
        code += "                       std::string* resp_bytes) -> ::protocomm::Status {\n";
        code += "                    ctx->set_method_name(\"" + full + "\");\n";
        code += "                    " + in + " req;\n";
        code += "                    ::protocomm::Status ps = ::protocomm::ParseProto(req_bytes, req);\n";
        code += "                    if (!ps.ok()) return ps;\n";
        code += "                    if (ctx->tracing())\n";
        code += "                        ctx->set_request_text(::protocomm::RenderProto(req));\n";
        code += "                    " + out + " resp;\n";
        code += "                    ::protocomm::Status s = this->" + m.name() + "(ctx, &req, &resp);\n";
        code += "                    if (!s.ok()) return s;\n";
        code += "                    if (ctx->tracing())\n";
        code += "                        ctx->set_response_text(::protocomm::RenderProto(resp));\n";
        code += "                    return ::protocomm::SerializeProto(resp, *resp_bytes);\n";
        code += "                });\n";
    }
    code += "        }\n";
    code += "    };\n";
}

void EmitFooter(std::string& code, const ServiceContext& ctx) {
    code += "};\n\n";              // close the service class
    if (ctx.has_ns) {
        code += "}  // namespace " + ctx.ns + "\n";
    }
}

}

void GenerateServiceFile(std::string& code, const ServiceContext& ctx) {
    EmitPreamble(code, ctx);
    code += "class " + ctx.svc_name + " final {\npublic:\n";
    EmitMethodConstants(code, ctx);
    EmitPeerWriterClass(code, ctx);
    EmitBroadcasterClass(code, ctx);
    EmitStubClass(code, ctx);
    EmitServiceClass(code, ctx);
    EmitFooter(code, ctx);
}

}  // namespace gen
}  // namespace protocomm
