package main

import (
	"fmt"
	"strconv"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		if err := checkHashCollisions(plugin); err != nil {
			return err
		}
		for _, f := range plugin.Files {
			if !f.Generate || len(f.Services) == 0 {
				continue
			}
			generateFile(plugin, f)
		}
		return nil
	})
}

func checkHashCollisions(plugin *protogen.Plugin) error {
	seen := make(map[uint32]string)
	for _, f := range plugin.Files {
		pkg := string(f.Desc.Package())
		for _, svc := range f.Services {
			protoSvc := string(svc.Desc.Name())
			for _, m := range svc.Methods {
				full := methodFullName(pkg, protoSvc, string(m.Desc.Name()))
				h := fnv1a32(full)
				if prev, ok := seen[h]; ok {
					if prev == full {
						continue
					}
					return fmt.Errorf(
						"protocomm: FNV1a32 method-ID collision between %q and %q. Rename one of the methods.",
						prev, full)
				}
				seen[h] = full
			}
		}
	}
	return nil
}

func pcIdent(name string) protogen.GoIdent {
	return protogen.GoIdent{GoName: name, GoImportPath: "github.com/boeing666/protocomm/go"}
}

func protoIdent(name string) protogen.GoIdent {
	return protogen.GoIdent{GoName: name, GoImportPath: "google.golang.org/protobuf/proto"}
}

func prototraceIdent(name string) protogen.GoIdent {
	return protogen.GoIdent{GoName: name, GoImportPath: "github.com/boeing666/protocomm/go/prototrace"}
}

func fnv1a32(s string) uint32 {
	h := uint32(0x811c9dc5)
	for i := 0; i < len(s); i++ {
		h ^= uint32(s[i])
		h *= 0x01000193
	}
	return h
}

func methodFullName(pkg, svc, method string) string {
	if pkg == "" {
		return "/" + svc + "/" + method
	}
	return "/" + pkg + "." + svc + "/" + method
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_protocomm.pb.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-protocomm-go. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, svc := range file.Services {
		genService(g, file, svc)
	}
}

func genService(g *protogen.GeneratedFile, file *protogen.File, svc *protogen.Service) {
	pkg := string(file.Desc.Package())
	protoSvc := string(svc.Desc.Name())
	goSvc := svc.GoName

	g.P("// Method IDs for ", goSvc, " service.")
	g.P("const (")
	for _, m := range svc.Methods {
		full := methodFullName(pkg, protoSvc, string(m.Desc.Name()))
		g.P("\t", goSvc, "_", m.GoName, "_MethodID uint32 = ",
			fmt.Sprintf("0x%08x", fnv1a32(full)), " // ", full)
	}
	g.P(")")
	g.P()

	genClient(g, svc, goSvc)
	genServerInterface(g, svc, goSvc)
	genUnimplementedServer(g, svc, goSvc)
	genRegister(g, svc, goSvc, protoSvc)
	genServiceWrapper(g, svc, goSvc)
}

func genClient(g *protogen.GeneratedFile, svc *protogen.Service, goSvc string) {
	client := goSvc + "Client"

	g.P("// ", client, " is the client stub for the ", goSvc, " service.")
	g.P("type ", client, " struct {")
	g.P("\tch *", pcIdent("Channel"))
	g.P("}")
	g.P()
	g.P("// New", client, " creates a client stub bound to the given channel.")
	g.P("func New", client, "(ch *", pcIdent("Channel"), ") *", client, " {")
	g.P("\treturn &", client, "{ch: ch}")
	g.P("}")
	g.P()

	for _, m := range svc.Methods {
		mid := goSvc + "_" + m.GoName + "_MethodID"
		in := m.Input.GoIdent
		out := m.Output.GoIdent

		g.P("func (c *", client, ") ", m.GoName, "(req *", in,
			") (*", out, ", ", pcIdent("Status"), ") {")
		g.P("\tdata, err := ", protoIdent("Marshal"), "(req)")
		g.P("\tif err != nil {")
		g.P("\t\treturn nil, ", pcIdent("Status"),
			"{Code: ", pcIdent("Internal"), ", Message: \"marshal: \" + err.Error()}")
		g.P("\t}")
		g.P("\trespData, st := c.ch.UnaryCall(", mid, ", data)")
		g.P("\tif !st.IsOK() {")
		g.P("\t\treturn nil, st")
		g.P("\t}")
		g.P("\tresp := new(", out, ")")
		g.P("\tif err := ", protoIdent("Unmarshal"), "(respData, resp); err != nil {")
		g.P("\t\treturn nil, ", pcIdent("Status"),
			"{Code: ", pcIdent("Internal"), ", Message: \"unmarshal: \" + err.Error()}")
		g.P("\t}")
		g.P("\treturn resp, ", pcIdent("StatusOK"), "()")
		g.P("}")
		g.P()
	}
}

func genServerInterface(g *protogen.GeneratedFile, svc *protogen.Service, goSvc string) {
	server := goSvc + "Server"

	g.P("// ", server, " is the server-side interface for the ", goSvc, " service.")
	g.P("type ", server, " interface {")
	for _, m := range svc.Methods {
		g.P("\t", m.GoName, "(ctx *", pcIdent("ServerContext"),
			", req *", m.Input.GoIdent, ") (*", m.Output.GoIdent, ", ", pcIdent("Status"), ")")
	}
	g.P("}")
	g.P()
}

func genUnimplementedServer(g *protogen.GeneratedFile, svc *protogen.Service, goSvc string) {
	uname := "Unimplemented" + goSvc + "Server"

	g.P("// ", uname, " returns UNIMPLEMENTED for every method.")
	g.P("type ", uname, " struct{}")
	g.P()

	for _, m := range svc.Methods {
		g.P("func (", uname, ") ", m.GoName, "(_ *", pcIdent("ServerContext"),
			", _ *", m.Input.GoIdent, ") (*", m.Output.GoIdent, ", ", pcIdent("Status"), ") {")
		g.P("\treturn nil, ", pcIdent("Status"),
			"{Code: ", pcIdent("Unimplemented"), ", Message: \"", m.GoName, " not implemented\"}")
		g.P("}")
		g.P()
	}
}

func genRegister(g *protogen.GeneratedFile, svc *protogen.Service, goSvc, protoSvc string) {
	server := goSvc + "Server"

	g.P("// Register", server, " registers a ", server, " with the protocomm server.")
	g.P("func Register", server, "(srv *", pcIdent("Server"), ", impl ", server, ") {")

	for _, m := range svc.Methods {
		mid := goSvc + "_" + m.GoName + "_MethodID"
		in := m.Input.GoIdent
		full := protoSvc + "." + string(m.Desc.Name())

		g.P("\tsrv.RegisterMethod(", mid,
			", func(ctx *", pcIdent("ServerContext"), ", data []byte) ([]byte, ", pcIdent("Status"), ") {")
		g.P("\t\tctx.MethodName = ", strconv.Quote(full))
		g.P("\t\treq := new(", in, ")")
		g.P("\t\tif err := ", protoIdent("Unmarshal"), "(data, req); err != nil {")
		g.P("\t\t\treturn nil, ", pcIdent("Status"),
			"{Code: ", pcIdent("Internal"), ", Message: \"unmarshal: \" + err.Error()}")
		g.P("\t\t}")
		g.P("\t\tif ctx.Trace {")
		g.P("\t\t\tctx.RequestText = ", prototraceIdent("Render"), "(req)")
		g.P("\t\t}")
		g.P("\t\tresp, st := impl.", m.GoName, "(ctx, req)")
		g.P("\t\tif !st.IsOK() {")
		g.P("\t\t\treturn nil, st")
		g.P("\t\t}")
		g.P("\t\tif ctx.Trace {")
		g.P("\t\t\tctx.ResponseText = ", prototraceIdent("Render"), "(resp)")
		g.P("\t\t}")
		g.P("\t\tout, err := ", protoIdent("Marshal"), "(resp)")
		g.P("\t\tif err != nil {")
		g.P("\t\t\treturn nil, ", pcIdent("Status"),
			"{Code: ", pcIdent("Internal"), ", Message: \"marshal: \" + err.Error()}")
		g.P("\t\t}")
		g.P("\t\treturn out, ", pcIdent("StatusOK"), "()")
		g.P("\t})")
	}

	g.P("}")
	g.P()
}

func genServiceWrapper(g *protogen.GeneratedFile, svc *protogen.Service, goSvc string) {
	server := goSvc + "Server"
	wrapper := unexport(goSvc) + "ServiceRegistrar"

	g.P("type ", wrapper, " struct{ impl ", server, " }")
	g.P()
	g.P("func (r *", wrapper, ") RegisterWith(srv *", pcIdent("Server"), ") {")
	g.P("\tRegister", server, "(srv, r.impl)")
	g.P("}")
	g.P()
	g.P("// New", goSvc, "Service wraps impl as a ", pcIdent("Service"),
		" for use with ServerBuilder.")
	g.P("func New", goSvc, "Service(impl ", server, ") ", pcIdent("Service"), " {")
	g.P("\treturn &", wrapper, "{impl: impl}")
	g.P("}")
	g.P()
}

func unexport(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'A' && r[0] <= 'Z' {
		r[0] = r[0] + ('a' - 'A')
	}
	return string(r)
}
